# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Shayer Tabs
tagline:          'The Jekyll Butler.'
description:      'A diligent and noble steward for building Jekyll sites.'
url:              https://ppmanforthewin.github.io/www

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
github:
  repo:           https://github.com/poole/www
